import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'


// ***** TODO: need to slap in the WebGL boilerplate in this file. Render a box on the screen, move it in render loop
// Then need to make the class that sorts boxes using the algorithm specified in constructor


function Home () {
    return (
        <div className={styles.container}>
            <Head>
                <title>Retort — Mehar Gaur</title>
                {/* <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" /> */}
            </Head>

            {/* Put WebGL <canvas> here */}

        </div>
    )
}

export default Home
